# Перечень volume
volumes:
  pg_data:
  static:
  media:

# Перечень контейнеров
services:
  db:
    image: postgres:17
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: amv13/foodgram_backend:latest
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media/
    depends_on:
      - db

  frontend:
    env_file: .env
    image: amv13/foodgram_gateway:latest
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    build: ./infra/
    volumes:
      - static:/staticfiles/
      - media:/etc/nginx/html/media/
    ports:
      - 8000:80
    depends_on:
      - backend