INGREDIENT_NAME_MAX_LENGTH = 128
MEASUREMENT_UNIT_MAX_LENGTH = 64
INGREDIENT_MIN_AMOUNT = 1
INGREDIENT_MAX_AMOUNT = 32767

RECIPE_MAX_LENGTH = 256
RECIPE_MIN_COOKING_TIME = 1
RECIPE_MAX_COOKING_TIME = 32767

USER_EMAIL_MAX_LENGTH = 254
USER_MAX_LENGTH = 150
USER_REGEX = r'^[\w.@+-]+$'
